update=Mon 23 Sep 2013 08:07:12 PM PDT
last_client=kicad
[eeschema]
version=1
PageLayoutDescrFile=
SubpartIdSeparator=0
SubpartFirstId=65
LibDir=/home/ted/kicad/projects/library
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=39
[eeschema/libraries]
LibName1=ted_capacitors
LibName2=ted_connectors
LibName3=TED_led
LibName4=ted_power
LibName5=ted_regulators
LibName6=ted_resistors
LibName7=ted_switches
LibName8=TED_transformer
LibName9=ted_transistor
LibName10=TED_zener
LibName11=ted_ic
LibName12=ted_inductors
LibName13=ted_crystals
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
[pcbnew/libraries]
LibName1=/home/ted/kicad/projects/library/ted_capacitors
LibName2=/home/ted/kicad/projects/library/ted_circuit_protect
LibName3=/home/ted/kicad/projects/library/TED_circuit_protect
LibName4=/home/ted/kicad/projects/library/ted_connectors
LibName5=/home/ted/kicad/projects/library/ted_crystals
LibName6=/home/ted/kicad/projects/library/ted_diodes
LibName7=/home/ted/kicad/projects/library/ted_ICs
LibName8=/home/ted/kicad/projects/library/ted_inductors
LibName9=/home/ted/kicad/projects/library/ted_regulators
LibName10=/home/ted/kicad/projects/library/ted_resistors
LibName11=/home/ted/kicad/projects/library/ted_sensors
LibName12=/home/ted/kicad/projects/library/ted_sockets
LibName13=/home/ted/kicad/projects/library/ted_switches
LibName14=/home/ted/kicad/projects/library/ted_transformers
LibName15=/home/ted/kicad/projects/library/ted_transistors
LibDir=
[general]
version=1
